//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoGeneralDetalle
    {
        public string DatoGeneralDetalleId { get; set; }
        public Nullable<int> DatoGeneralId { get; set; }
        public Nullable<int> ValorTabla { get; set; }
        public string Descripcion { get; set; }
        public string ValorTexto1 { get; set; }
        public string ValorTexto2 { get; set; }
        public Nullable<int> ValorEntero { get; set; }
        public Nullable<decimal> ValorDecimal { get; set; }
        public Nullable<decimal> ValorFecha { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
