//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDControlMGEntities : DbContext
    {
        public BDControlMGEntities()
            : base("name=BDControlMGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<DatoGeneral> DatoGeneral { get; set; }
        public virtual DbSet<DatoGeneralDetalle> DatoGeneralDetalle { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<OperacionCalculadora> OperacionCalculadora { get; set; }
    
        public virtual ObjectResult<Usp_ListaCatalogo_Result> Usp_ListaCatalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_ListaCatalogo_Result>("Usp_ListaCatalogo");
        }
    
        public virtual ObjectResult<Usp_getUltimaConfCaja_Result> Usp_getUltimaConfCaja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_getUltimaConfCaja_Result>("Usp_getUltimaConfCaja");
        }
    
        public virtual ObjectResult<Usp_obtenerConfCaja_Result> Usp_obtenerConfCaja(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_obtenerConfCaja_Result>("Usp_obtenerConfCaja", usuarioParameter);
        }
    
        public virtual ObjectResult<Usp_ReporteOperacion_Result> Usp_ReporteOperacion(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> tipoOperacion, Nullable<int> eliminado, string usuario)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var tipoOperacionParameter = tipoOperacion.HasValue ?
                new ObjectParameter("TipoOperacion", tipoOperacion) :
                new ObjectParameter("TipoOperacion", typeof(int));
    
            var eliminadoParameter = eliminado.HasValue ?
                new ObjectParameter("Eliminado", eliminado) :
                new ObjectParameter("Eliminado", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_ReporteOperacion_Result>("Usp_ReporteOperacion", fechaIniParameter, fechaFinParameter, tipoOperacionParameter, eliminadoParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<Usp_ListarUsuarios_Result> Usp_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_ListarUsuarios_Result>("Usp_ListarUsuarios");
        }
    }
}
