//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int IdMovimiento { get; set; }
        public Nullable<decimal> MontoMovimiento { get; set; }
        public string ComentarioMovimiento { get; set; }
        public Nullable<int> TipoMovimiento { get; set; }
        public string UsuarioCreacion { get; set; }
        public string FechaCreacion { get; set; }
    }
}
