//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int IdOperacion { get; set; }
        public Nullable<decimal> MontoIngreso { get; set; }
        public Nullable<int> TipoOperacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Moneda { get; set; }
        public Nullable<int> MonedaDe { get; set; }
        public Nullable<int> MonedaA { get; set; }
        public Nullable<bool> FlagSumaCajaSol { get; set; }
        public Nullable<bool> FlagRestaCajaSol { get; set; }
        public Nullable<bool> FlagSumaCajaDolar { get; set; }
        public Nullable<bool> FlagRestaCajaDolar { get; set; }
        public Nullable<bool> FlagSumaCajaEuro { get; set; }
        public Nullable<bool> FlagRestaCajaEuro { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<System.DateTime> HoraMovimiento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<decimal> MontoSalida { get; set; }
    }
}
